apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
