{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.api.serviceAccount.gcpServiceAccount | quote }}
{{- end }}
