apiVersion: v1
kind: Secret
metadata:
  name: sso-api-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.api.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  APP_CORS_ALLOWED_ORIGINS: {{ .Values.cors.allowedOrigins | quote }}
