apiVersion: v1
kind: Service
metadata:
  name: sso-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: sso-api
spec:
  selector:
    app: sso-api
  ports:
    - name: http
      port: 8076
      targetPort: 8076
  type: ClusterIP
