{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-frontend
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    {{- if .Values.frontend.ingress.managedCert.enabled }}
    networking.gke.io/managed-certificates: {{ .Values.frontend.ingress.managedCert.name | quote }}
    {{- end }}
    {{- if .Values.frontend.ingress.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.frontend.ingress.staticIpName | quote }}
    {{- end }}
    networking.gke.io/v1beta1.FrontendConfig: "sso-frontend"
spec:
  defaultBackend:
    service:
      name: sso-frontend
      port:
        number: 80
{{- end }}
---
{{- if and .Values.frontend.ingress.enabled .Values.frontend.ingress.managedCert.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.frontend.ingress.managedCert.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  domains:
    {{- range .Values.frontend.ingress.managedCert.domains }}
    - {{ . }}
    {{- end }}
{{- end }}
