apiVersion: v1
kind: Secret
metadata:
  name: sso-postgres-secret
  namespace: sso-staging
type: Opaque
stringData:
  POSTGRES_DB: intelli_sso
  POSTGRES_USER: postgres-admin
  POSTGRES_PASSWORD: changeme-sso-db-password
