apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sso-postgres
  namespace: sso-staging
spec:
  serviceName: sso-postgres
  replicas: 1
  selector:
    matchLabels:
      app: sso-postgres
  template:
    metadata:
      labels:
        app: sso-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: sso-postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres-admin
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 10Gi
