apiVersion: v1
kind: Secret
metadata:
  name: teamcity-postgres-secret
  namespace: cicd
type: Opaque
stringData:
  POSTGRES_DB: teamcity
  POSTGRES_USER: teamcity
  # Change this before deploying!
  POSTGRES_PASSWORD: changeme-teamcity-db-password
