apiVersion: v1
kind: Service
metadata:
  name: sso-frontend
  namespace: {{ .Values.global.namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    {{- if .Values.frontend.service.annotations }}
    {{- toYaml .Values.frontend.service.annotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: sso-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
